// ENUMS DO BANCO DE DADOS

export const TIPO_USUARIO = {
  ADMIN: 'ADMIN',
  EMPRESA: 'EMPRESA',
  FREELANCER: 'FREELANCER'
};

export const STATUS_PROJETO = {
  PLANEJAMENTO: 'PLANEJAMENTO',
  EM_ANDAMENTO: 'EM_ANDAMENTO',
  CONCLUIDO: 'CONCLUIDO',
  CANCELADO: 'CANCELADO'
};

export const STATUS_ATIVIDADE = {
  PENDENTE: 'PENDENTE',
  EM_ANDAMENTO: 'EM_ANDAMENTO',
  CONCLUIDA: 'CONCLUIDA',
  CANCELADA: 'CANCELADA'
};

export const STATUS_TAREFA = {
  PENDENTE: 'PENDENTE',
  EM_PROGRESSO: 'EM_PROGRESSO',
  AGUARDANDO_ENTREGA: 'AGUARDANDO_ENTREGA',
  ENTREGA_RECEBIDA: 'ENTREGA_RECEBIDA',
  APROVADA: 'APROVADA',
  REVISAO_NECESSARIA: 'REVISAO_NECESSARIA',
  CONCLUIDA: 'CONCLUIDA',
  CANCELADA: 'CANCELADA'
};

export const STATUS_ENTREGA = {
  AGUARDANDO_APROVACAO: 'AGUARDANDO_APROVACAO',
  APROVADA: 'APROVADA',
  REVISAO_NECESSARIA: 'REVISAO_NECESSARIA',
  REJEITADA: 'REJEITADA'
};

export const STATUS_PAGAMENTO = {
  PENDENTE: 'PENDENTE',
  PROCESSANDO: 'PROCESSANDO',
  PAGO: 'PAGO',
  CANCELADO: 'CANCELADO'
};

export const STATUS_CONTRATO = {
  ATIVO: 'ATIVO',
  CONCLUIDO: 'CONCLUIDO',
  CANCELADO: 'CANCELADO'
};

export const PRIORIDADE_TAREFA = {
  BAIXA: 'BAIXA',
  MEDIA: 'MEDIA',
  ALTA: 'ALTA',
  URGENTE: 'URGENTE'
};

export const METODO_PAGAMENTO = {
  PIX: 'PIX',
  TRANSFERENCIA: 'TRANSFERENCIA',
  DINHEIRO: 'DINHEIRO',
  OUTRO: 'OUTRO'
};

export const TIPO_NOTIFICACAO = {
  TAREFA_ATRIBUIDA: 'TAREFA_ATRIBUIDA',
  ENTREGA_RECEBIDA: 'ENTREGA_RECEBIDA',
  ENTREGA_APROVADA: 'ENTREGA_APROVADA',
  REVISAO_SOLICITADA: 'REVISAO_SOLICITADA',
  PAGAMENTO_EFETUADO: 'PAGAMENTO_EFETUADO',
  PRAZO_PROXIMO: 'PRAZO_PROXIMO',
  PRAZO_VENCIDO: 'PRAZO_VENCIDO',
  COMENTARIO_NOVO: 'COMENTARIO_NOVO'
};

export const ACAO_LOG = {
  CRIOU: 'CRIOU',
  ATUALIZOU: 'ATUALIZOU',
  EXCLUIU: 'EXCLUIU',
  APROVOU: 'APROVOU',
  REJEITOU: 'REJEITOU',
  PAGOU: 'PAGOU',
  CANCELOU: 'CANCELOU',
  ATRIBUIU: 'ATRIBUIU',
  COMENTOU: 'COMENTOU'
};

// LABELS PARA UI

export const LABELS_STATUS_PROJETO = {
  [STATUS_PROJETO.PLANEJAMENTO]: 'Planejamento',
  [STATUS_PROJETO.EM_ANDAMENTO]: 'Em Andamento',
  [STATUS_PROJETO.CONCLUIDO]: 'Concluído',
  [STATUS_PROJETO.CANCELADO]: 'Cancelado'
};

export const LABELS_STATUS_TAREFA = {
  [STATUS_TAREFA.PENDENTE]: 'Pendente',
  [STATUS_TAREFA.EM_PROGRESSO]: 'Em Progresso',
  [STATUS_TAREFA.AGUARDANDO_ENTREGA]: 'Aguardando Entrega',
  [STATUS_TAREFA.ENTREGA_RECEBIDA]: 'Entrega Recebida',
  [STATUS_TAREFA.APROVADA]: 'Aprovada',
  [STATUS_TAREFA.REVISAO_NECESSARIA]: 'Revisão Necessária',
  [STATUS_TAREFA.CONCLUIDA]: 'Concluída',
  [STATUS_TAREFA.CANCELADA]: 'Cancelada'
};

export const LABELS_PRIORIDADE = {
  [PRIORIDADE_TAREFA.BAIXA]: 'Baixa',
  [PRIORIDADE_TAREFA.MEDIA]: 'Média',
  [PRIORIDADE_TAREFA.ALTA]: 'Alta',
  [PRIORIDADE_TAREFA.URGENTE]: 'Urgente'
};

export const LABELS_METODO_PAGAMENTO = {
  [METODO_PAGAMENTO.PIX]: 'PIX',
  [METODO_PAGAMENTO.TRANSFERENCIA]: 'Transferência Bancária',
  [METODO_PAGAMENTO.DINHEIRO]: 'Dinheiro',
  [METODO_PAGAMENTO.OUTRO]: 'Outro'
};

// CORES PARA BADGES

export const CORES_STATUS_PROJETO = {
  [STATUS_PROJETO.PLANEJAMENTO]: '#3b82f6', // azul
  [STATUS_PROJETO.EM_ANDAMENTO]: '#f59e0b', // amarelo
  [STATUS_PROJETO.CONCLUIDO]: '#10b981', // verde
  [STATUS_PROJETO.CANCELADO]: '#ef4444' // vermelho
};

export const CORES_STATUS_TAREFA = {
  [STATUS_TAREFA.PENDENTE]: '#6b7280', // cinza
  [STATUS_TAREFA.EM_PROGRESSO]: '#3b82f6', // azul
  [STATUS_TAREFA.AGUARDANDO_ENTREGA]: '#f59e0b', // amarelo
  [STATUS_TAREFA.ENTREGA_RECEBIDA]: '#8b5cf6', // roxo
  [STATUS_TAREFA.APROVADA]: '#10b981', // verde
  [STATUS_TAREFA.REVISAO_NECESSARIA]: '#f97316', // laranja
  [STATUS_TAREFA.CONCLUIDA]: '#059669', // verde escuro
  [STATUS_TAREFA.CANCELADA]: '#ef4444' // vermelho
};

export const CORES_PRIORIDADE = {
  [PRIORIDADE_TAREFA.BAIXA]: '#10b981', // verde
  [PRIORIDADE_TAREFA.MEDIA]: '#f59e0b', // amarelo
  [PRIORIDADE_TAREFA.ALTA]: '#f97316', // laranja
  [PRIORIDADE_TAREFA.URGENTE]: '#ef4444' // vermelho
};

// OPTIONS PARA SELECTS

export const OPTIONS_STATUS_PROJETO = [
  { value: STATUS_PROJETO.PLANEJAMENTO, label: LABELS_STATUS_PROJETO[STATUS_PROJETO.PLANEJAMENTO] },
  { value: STATUS_PROJETO.EM_ANDAMENTO, label: LABELS_STATUS_PROJETO[STATUS_PROJETO.EM_ANDAMENTO] },
  { value: STATUS_PROJETO.CONCLUIDO, label: LABELS_STATUS_PROJETO[STATUS_PROJETO.CONCLUIDO] },
  { value: STATUS_PROJETO.CANCELADO, label: LABELS_STATUS_PROJETO[STATUS_PROJETO.CANCELADO] }
];

export const OPTIONS_PRIORIDADE = [
  { value: PRIORIDADE_TAREFA.BAIXA, label: LABELS_PRIORIDADE[PRIORIDADE_TAREFA.BAIXA] },
  { value: PRIORIDADE_TAREFA.MEDIA, label: LABELS_PRIORIDADE[PRIORIDADE_TAREFA.MEDIA] },
  { value: PRIORIDADE_TAREFA.ALTA, label: LABELS_PRIORIDADE[PRIORIDADE_TAREFA.ALTA] },
  { value: PRIORIDADE_TAREFA.URGENTE, label: LABELS_PRIORIDADE[PRIORIDADE_TAREFA.URGENTE] }
];

export const OPTIONS_METODO_PAGAMENTO = [
  { value: METODO_PAGAMENTO.PIX, label: LABELS_METODO_PAGAMENTO[METODO_PAGAMENTO.PIX] },
  { value: METODO_PAGAMENTO.TRANSFERENCIA, label: LABELS_METODO_PAGAMENTO[METODO_PAGAMENTO.TRANSFERENCIA] },
  { value: METODO_PAGAMENTO.DINHEIRO, label: LABELS_METODO_PAGAMENTO[METODO_PAGAMENTO.DINHEIRO] },
  { value: METODO_PAGAMENTO.OUTRO, label: LABELS_METODO_PAGAMENTO[METODO_PAGAMENTO.OUTRO] }
];

// CONFIGURAÇÕES

export const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB
export const ALLOWED_FILE_TYPES = [
  'image/jpeg',
  'image/png',
  'image/gif',
  'application/pdf',
  'application/zip',
  'text/plain',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
];

export const DATE_FORMAT = 'DD/MM/YYYY';
export const DATETIME_FORMAT = 'DD/MM/YYYY HH:mm';
export const CURRENCY_FORMAT = 'pt-BR';
export const CURRENCY = 'BRL';

// MENSAGENS PADRÃO

export const MENSAGENS = {
  SUCESSO: {
    PROJETO_CRIADO: 'Projeto criado com sucesso!',
    PROJETO_ATUALIZADO: 'Projeto atualizado com sucesso!',
    PROJETO_CANCELADO: 'Projeto cancelado com sucesso!',
    TAREFA_CRIADA: 'Tarefa criada com sucesso!',
    ENTREGA_ENVIADA: 'Entrega enviada com sucesso!',
    ENTREGA_APROVADA: 'Entrega aprovada com sucesso!',
    PAGAMENTO_REGISTRADO: 'Pagamento registrado com sucesso!',
    COMENTARIO_ADICIONADO: 'Comentário adicionado com sucesso!'
  },
  ERRO: {
    GENERICO: 'Ocorreu um erro. Tente novamente.',
    CAMPOS_OBRIGATORIOS: 'Preencha todos os campos obrigatórios.',
    ARQUIVO_MUITO_GRANDE: 'Arquivo muito grande. Máximo 10MB.',
    TIPO_ARQUIVO_INVALIDO: 'Tipo de arquivo não permitido.',
    SEM_PERMISSAO: 'Você não tem permissão para realizar esta ação.'
  }
};